version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8088
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=demo
      - DJANGO_DB_USER=demo
      - DJANGO_DB_PASSWORD=demo
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
